kind: pipeline
name: default

steps:
- name: test 
  image: golang
  commands:
  - go test -parallel 10 ./... 

- name: golangci-lint
  image: golangci/golangci-lint:v1.39
  commands:
  - golangci-lint run
